
# Submission script

# DO NOT EDIT THIS FILE

import tarfile, re, os
from pathlib import Path

ASSIGNMENT_DIR = Path(__file__).parent.parent

error = False
solution_filename = 'solution-hw1.tar.gz'

with tarfile.open(ASSIGNMENT_DIR / solution_filename, 'w:gz') as t:
    def try_add(f, default_len = 0):
        global error
        try:
            s = os.stat(ASSIGNMENT_DIR / f)
            if default_len != 0 and s.st_size == default_len:
                print(f"Warning: did you complete {f}?")
            if f == 'README.txt':
                for l in open(ASSIGNMENT_DIR / "README.txt").readlines():
                    if re.match(r'^id:\s*\d{8}\s*$', l):
                        break
                else:
                    print("Warning: did you put your id in README.txt?")
            t.add(name=ASSIGNMENT_DIR / f, arcname=f)
        except FileNotFoundError:
            print(f"Error: missing {f}")
            error = True

    try_add('README.txt')
    try_add('ski_eval.py', 215)
    try_add('problem.ski', 1759)

if not error:
    print(f"Wrote '{ASSIGNMENT_DIR / solution_filename}'. Upload this file to Canvas.")
else:
    os.unlink(ASSIGNMENT_DIR / solution_filename)
    print(f'Try again after fixing the above error(s)!')
